config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get 'server_error' => 'static_pages#server_error'

  get 'signup' => 'users#new'
  get 'ranking' => 'users#ranking'
  get 'delete_profile_image' => 'users#delete_profile_image'
  get 'battles/ranking' => 'battles#ranking'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#log_user_in'
  delete 'logout' => 'sessions#log_user_out'

  get 'questions' => 'questions#category'
  get 'questions/all' => 'questions#index'

  get 'questions/humans' => 'questions#humans'
  get 'questions/nature' => 'questions#nature'
  get 'questions/languages' => 'questions#languages'
  get 'questions/math' => 'questions#math'
  get 'questions/recommended' => 'questions#recommended'
  get 'questions/upload' => 'questions#new'
  post 'questions/upload_questions'
  post 'questions/upload_candidates_data'

  get 'medals' => 'medals#index'

  get '/generate_random_user', :to=>"battles#generate_random_user"

  get 'notifications' => 'notifications#index'

  get 'answer_exam' => 'exams#answer_exam'
  get 'select_exam' => 'exams#select_exam'
  get 'exam_result' => 'exams#exam_result'
  get 'exams_statistics' => 'exams#exams_statistics'
  delete 'cancel_exam' => 'exams#cancel_exam'

  resources :posts
  resources :comments

  post 'comments/create' => 'comments#create'

  resources :topics
  resources :posts do
    resources :comments
  end

  resources :users
  resources :questions do
    member do
      post 'answer'
      post 'next' => 'questions#next_question'
    end
  end

  resources :battles do
    member do
      post 'answer'
      get 'finish'
    end
  end

  resources :posts do
    member do
      get 'rate_post' => 'posts#rate_post'
    end
  end

  resources :comments do
    member do
      get 'rate_comment' => 'comments#rate_comment'
    end
  end

  resources :battles do
    member do
      get 'result' => 'battles#result'
    end
  end

  resources :notifications do
    get :read, on: :collection
  end

  scope "(:locale)", locale: /en|nl/ do
    resources :users
    resources :battles
    resources :posts
    resources :comments
    resources :battles
    resources :altenatives
    resources :candidates
    resources :exams
    resources :medals
    resources :notifications
    resources :questions
    resources :texts
    resources :topics
  end

  get '*unmatched_route', :to => 'application#raise_not_found!'

end

app/controllers/questions_controller.rb
# File: questions_controller.rb
# Purpose: Maintain logic for questions.
# License: LGPL. No copyright.

# This controller sets the behavior for showing questons to user.


class QuestionsController < ApplicationController

  before_action :authenticate_user
  before_action :authenticate_admin, only: [:new, :create, :edit, :destroy, :update]

  include QuestionsHelper

 # name: index
 # explanation: this method order questions by year and number
 # parameters: 
 # -none
 # return: questions of enemamigo
  def index
    @questions ||= Question.all.order(:year, :number)
    assert(@questions.kind_of?(Question))
    return @questions
  end

 # name: edit
 # explanation: this method retrieves a single question from id and rertun it to edit view
 # parameters:
 # -none
 # return: question of enemamigo
  def edit
    @question ||= Question.find(params[:id])
    assert(@questions.kind_of?(Question))
    return @questions
  end

 # name: update
 # explanation: this method retrieves a single question from id and update it 
 # parameters:
 # -none
 # return: question of enemamigo
  def update
    @question ||= Question.find(params[:id])
    assert(@questions.kind_of?(Question))
    check_update ||= @question.update_attributes(question_params)
    if check_update
      flash[:success] = t(:update_question)
      return redirect_to question_path
    else
      return render('edit')
    end
  end

 # name: show
 # explanation: this method order questions 
 # parameters:
 # -none
 # return: questions of enemamigo
  def show
    @question ||= Question.find(params[:id])
    assert(@questions.kind_of?(Question))
    return @question
  end

 # name: edit
 # explanation: this method order questions 
 # parameters:
 # -none
 # return: questions of enemamigo
  def destroy
    @question ||= Question.find(params[:id])
    assert(@questions.kind_of?(Question))
    @question.destroy
    flash[:success] = t(:delete_question)
    return redirect_to questions_path
  end

 # name: answer
 # explanation: this method order questions 
 # parameters:
 # -none
 # return: questions of enemamigo
  def answer
    question ||= Question.find(params[:id])
    assert(questions.kind_of?(Question))
    @answer_letter ||= params[:alternative]

    if params[:alternative].blank?
      redirect_to_back(root_path)
    else
      current_user.update_attribute(:tried_questions, current_user.tried_questions << question.id)
      question.update_attribute(:users_tries, question.users_tries + 1)

      @correct_answer ||= (@answer_letter == question.right_answer)

      respond_to do |format|
        format.html { redirect_to questions_path }
        format.js { @correct_answer }
      end

      if @correct_answer
        question.update_attribute(:users_hits, question.users_hits + 1)
      
        question_include ||= current_user.accepted_questions.include? question.id
        if !question_include
          current_user.accepted_questions.push(question.id)
          current_user.update_attribute(:points, current_user.points + 4)
        else 
          # nothing to do 
        end
      end
    end
  end

 # name: category
 # explanation: this method  associate category view with this controller
 # parameters:
 # -none
 # return: category
  def category
  end

 # name: nature
 # explanation: this method searches for questions from specific area   
 # parameters:
 # -none
 # return: questions of enemamigo
  def nature
    @questions ||= Question.where(area: "ciências da natureza e suas tecnologias").order(:year, :number)
    assert(@questions.kind_of?(Question))
    return @questions
  end

 # name: humans
 # explanation: this method searches for questions from specific area  
 # parameters:
 # -none 
 # return: questions of enemamigo
  def humans
    @questions ||= Question.where(area: "ciências humanas e suas tecnologias").order(:year, :number)
    assert(@questions.kind_of?(Question))
    return @questions
  end

 # name: languages
 # explanation: this method searches for questions from specific area  
 # parameters:
 # -none
 # return: questions of enemamigo
  def languages
    @questions ||= Question.where(area: "linguagens, códigos e suas tecnologias").order(:year, :number)
    assert(@questions.kind_of?(Question))
    return @questions
  end

 # name: math
 # explanation: this method searches for questions from specific area  
 # parameters:
 # -none
 # return: questions of enemamigo
  def math
    @questions ||= Question.where(area: "matemática e suas tecnologias").order(:year, :number)
    assert(@questions.kind_of?(Question))
    return @questions
  end

 # name: recommended
 # explanation: this method searches for questions from recommended 
 # parameters:
 # -none
 # return: questions of enemamigo
  def recommended
    areas ||= ["ciências da natureza e suas tecnologias",
             "ciências humanas e suas tecnologias",
             "linguagens, códigos e suas tecnologias",
             "matemática e suas tecnologias"]
    @questions ||= []
    areas.each do |area|
      classification = current_user.classification(area)
      @questions ||= @questions | instance_eval("Question.#{classification}_questions('#{area}')")
      return @questions
    end
    
    @questions ||= @questions.select { |q| !current_user.accepted_questions.include? q.id }
    return @questions
  end

 # name: upload_questions
 # explanation: this method upload questions the enemamigo
 # parameters:
 # -none
 # return: redirect_to questions_path
  def upload_questions
    uploaded_file = params[:questions_file]

    if uploaded_file.nil?
      raise Exception
    else
      # nothing to do 
    end

    file_content = uploaded_file.read
      assert(file_content.nil? == false)
    Parser.read_questions(file_content)

    flash[:success] = t(:upload_message_question)
    return redirect_to questions_path
  end

 # name: upload_candidates_data
 # explanation: this method upload data from candidates 
 # parameters:
 # -none
 # return:redirect_to Question.find(params[:id]).next_questionh
  def upload_candidates_data
    uploaded_file = params[:candidates_data_file]

   if uploaded_file.nil?
      raise Exception
   else
      # nothing to do
    end

    file_content = uploaded_file.read

    Parser.read_candidates_data(file_content, params[:test_year])

    flash[:success] = t(:upload_message_data)
    return redirect_to questions_path
  end

 # name: next_questions
 # explanation: this method redirects to next question 
 # parameters:
 # -none
 # return:redirect_to Question.find(params[:id]).next_questionh
  def next_question
    return redirect_to Question.find(params[:id]).next_question
    assert(@questions.kind_of?(Question))
  end

  private

 # name: question_params
 # explanation: this method udes to collet all the fields from object questions
 # parameters:
 # -none
 # return: question_params
  def question_params
    params.require(:question).permit(:year, :area, :number, :enunciation, :reference, :image, :right_answer, :alternatives_attributes => [:id, :letter, :description])
  end

end

app/helpers/questions_helper.rb
# File: questions_helper.rb
# Purpose: Maintain additional logic for questions.
# License: LGPL. No copyright.

# This helper contains the method that parses information into the system.

module QuestionsHelper

  class Parser
    class << self
    # name: read_questions
    # explanation: creates questions and topics to these questions on the system
    # based on a JSON file
    # parameters:
    # -json_questions: A JSON file with questions from exam
    # return: none
    def read_questions(json_questions)
      questions = JSON.parse(json_questions)["questions"]

      questions.each do |question|
        system_question = Question.new

        question.each do |attr, value|
          parse_system_question(attribute, value)
        end

        system_question.save
        topic_for_system_question = create_topic(system_question)
      end
    end

    NUMBER_OF_QUESTIONS_IN_A_EXAM = 180

      # name: read_candidates_data
      # explanation: method to create info about real student's performance in
      # questions.
      # parameters:
      # -candidates_data: a JSON file with real student's performance
      # -test_year: the year of the exam
      # return: none
      def read_candidates_data(candidates_data, test_year)
        candidates_data.each_line do |line|
          if line != "\n"
            student_responses = regex_to_find_student_response(line)
            enem_feedback = regex_to_find_enem_feedback(line)
            text_booklet_types = regex_to_find_test_booklet_types(line)
            test_booklet_types_array = test_booklet_types.scan(/.{3}/)

            language_choice = enem_feedback.slice!(0).to_i
            enem_feedback.slice!(95 - (5 * language_choice), 5)
            student_hits = 0
            i = 0

            parse_questions_response(test_year, student_hits, enem_feedback, students_responses)

            create_candidate(student_hits)
          else
            # nothing to do
          end
        end
      end

      # name: parse_questions_response
      # explanation: method to create info about real student's tries and accepted
      # answers.
      # parameters:
      # - test_year: the year of the exam
      # - enem_feedback: questions of ENEM
      # - student_hits: number of questions a student got right
      # - students_responses: questions a student tried to answer
      # return: void
      def parse_questions_response(test_year, student_hits, enem_feedback, students_responses)
        for i in 0...NUMBER_OF_QUESTIONS_IN_A_EXAM
          question = Question.where(number: i, year: test_year).take

          if !question.nil?
            if student_responses[i] == enem_feedback[i]
              student_hits = student_hits + 1
              question.hits = question.hits + 1
            end

            question.tries = question.tries + 1
            question.save
          else
            # nothing to do
          end
        end
      end

      def parse_system_question(attribute, value)
        if attribute == "text"
          value.each do |text|
            new_text = create_text(text)
            system_question.texts << new_text
          end
        elsif attribute == "alternatives"
          create_alternatives(system_question)
        else
          eval "system_question.#{attr} = value"
        end
      end

      # name: create_alternatives
      # explanation: creates alternatives for questions for user  the system
      # questions.
      # parameters:
      # -candidates_data: a JSON file with a JSON file with alternatives for questions for user  the system
      # return: none
       def create_alternatives(system_question)
        5.times do |i|
          system_question.alternatives.build
          system_question.alternatives[i].letter = value.keys[i]
          system_question.alternatives[i].deion = value[value.keys[i]]
        end
      end

      # name: create_topic
      # explanation: creates a topic for a question in the system
      # parameters:
      # - system_question: a question from the system
      # return: topic
			def create_topic(system_question)
				topic_name = "Questão #{system_question.number} - Ano #{system_question.year}"
				topic_deion = "Dúvidas e respostas sobre a questão #{system_question.number} da prova do ano #{system_question.year}"

				new_topic = Topic.create(name: topic_name, question_id: system_question.id, deion: topic_deion)

				return new_topic
			end

      # name: create_text
      # explanation: creates a text with given json hash
      # parameters:
      # - text: hash extracted from a json file
      # return: object of type Text
      def create_text(text)
        new_text = Text.new(title: text["title"], paragraphs: text["paragraphs"], reference: text["reference"])

        return new_text
      end

      # name: create candidate
      # explanation: creates a candidate based on a real candidate of ENEM with
      # a average of questions hit
      # parameters:
      # - student_hits: questions a real candidate got right
      # return: Candidate
      def create_candidate(student_hits)
        average = (100 * student_hits.to_f / 180).round(2)

        Candidate.create(general_average: average)

        return Candidate
      end

      # name: regex_to_find_student_response
      # explanation: use a regex to find a response from a real student in a json
      # file
      # parameters:
      # - line: line of the json file
      # return: hash
      def regex_to_find_student_response(line)
        student_response = line[/(A|B|C|D|E|'*'){180}/, 0]

        return student_response
      end

      # name: regex_to_find_enem_feedback
      # explanation: use a regex to find enem feedback of a json line
      # parameters:
      # - line: line of the json file
      # return: hash
      def regex_to_find_enem_feedback(line)
        enem_feedback = line[/(0|1){1}(A|B|C|D|E){185}/, 0]

        return enem_feedback
      end

      # name: regex_to_find_test_booklet_types
      # explanation: use a regex to find test booklet types of a json line
      # parameters:
      # - line: line of the json file
      # return: hash
      def regex_to_find_test_booklet_types(line)
        test_booklet_types = line[/[0-9]{13}(A|B|C|D|E){185}/, 0]

        return test_booklet_types
      end
    end
  end
end

app/views/questions/_category.html.erb
<!--
  File: _category.html.erb
  Purpose: This View that shows the year, the number and the wording of the question.
  License : LGPL. No copyright.
 -->

<% if !@questions.blank? %>

  <table class='table'>

    <thead>
      <th>Ano</th>
      <th>Número</th>
      <th>Enunciado</th>
    </thead>

    <% @questions.each do |questions| %>

      <tr>
        <td><%= questions.year %></td>
        <td><%= link_to (questions.number, "/questions/#{t.id}") %></td>
        <td><%= questions.enunciation %></td>
      </tr>
      
    <% end %>
  </table>

<% else %> 
  <!-- nothing to do -->

  <h3> Não existem recomendações de questões no momento. </h3>

<% end %>

app/views/questions/_form.html.erb
<!--
  File: _form.html.erb
  Purpose: This View that shows the year, the number, the area, the image, the letter, right_answer and the wording of the question.
  License : LGPL. No copyright.
 -->

<%= form_for(@question) do |form_for| %>

	<div>
		<%= form_for.label :year %>
		<%= form_for.text_field :year %>
	</div>
	<div>
		<%= form_for.label :area %>
		<%= form_for.text_field :area %>
	</div>
	<div>
		<%= form_for.label :number %>
		<%= form_for.text_field :number %>
	</div>
	<div>
		<%= form_for.label :enunciation %>
		<%= form_for.text_field :enunciation %>
	</div>
	<div>
		<%= form_for.label :reference %>
		<%= form_for.text_field :reference %>
	</div>
	<div>
		<%= form_for.label :image %>
		<%= form_for.text_field :image %>
	</div>

	<%= form_for.fields_for :alternatives do |fields_for| %>
		<div>
			<%= fields_for.label :letter %>
			<%= fields_for.text_field :letter %>

			<%= fields_for.label :description %>
			<%= fields_for.text_field :description %>
		</div>
	<% end %>
	<div>
		<%= form_for.label :right_answer %>
		<%= form_for.text_field :right_answer %>
	</div>

	<%= form_for.submit %>

<% end %>

app/views/questions/answer.js.erb
$('input.btn').hide();
$('input[type="radio"]').hide();
$('#jump-btn').html('Próxima questão');
$('#jump-btn').after("<%= j link_to 'Fórum', topic_path, class: 'btn btn-primary btn-sm button' %>");
$(".<%= j @answer_letter %>-description").after("<div class='alert alert-info'><%= j image_tag(@correct_answer ? 'correct-answer' : 'wrong-answer', alt: "", class: 'answer-feedback') %><%= @correct_answer ? 'Parabéns! Você ganhou 4 pontos!' : 'Você errou, tente novamente' %></div>");

app/views/questions/category.html.erb
<!--
  File: category.erb
  Purpose: This View that direct the link to image of the question.
  License : LGPL. No copyright.
 -->

<h1 class="content-title"> Categorias </h1>

<table class="category-images">

	<tr>
		<td><%= link_to image_tag("humanas.png"), questions_humans_path %></td>
		<td><%= link_to image_tag("natureza.png"), questions_nature_path %></td>
		<td><%= link_to image_tag("linguagens.png"), questions_languages_path %></td>
	</tr>
	
	<tr>
		<td><%= link_to image_tag("matematica.png"), questions_math_path %></td>
		<td><%= link_to image_tag("todas.png"), questions_all_path %></td>
        <td><%= link_to image_tag("sugeridas.png"), questions_recommended_path %></td>
	</tr>

</table>

app/views/questions/edit.html.erb
<!--
  File: edit.erb
  Purpose: This View that show the page editing of the question.
  License : LGPL. No copyright.
 -->

<h1>Edit question <%= @question.id %> (number <%= @question.number%>)</h1>

<%if !@question.errors.empty?%>
  <% flash.now[:danger] = @question.errors.full_messages.join("<br/>").html_safe %>
  
<% end %>

<%else%>
	<!-- nothing to do -->

<%= render :partial => 'form' %>

app/views/questions/humans.html.erb
<!--
  File: humans.erb
  Purpose: This View that show the humans category of the question.
  License : LGPL. No copyright.
 -->

<h1>Ciências Humanas e suas Tecnologias</h1>

<%= render :partial => 'category' %>

app/views/questions/index.html.erb
<!--
  File: languages.erb
  Purpose: This View that show the list of the question.
  License : LGPL. No copyright.
 -->

<h1> Lista de Questões </h1>

<% if current_user.role_admin? %>
	<%= link_to ('Novas Questões', new_question_path, class: "btn btn-success")  %>

<% end %>
	<%else%>
		<!-- nothing to do -->

<% if !@questions.blank? %>
	<table class='table'>
		<thead>
			<th>Ano</th>
			<th>Número</th>
			<th>Área</th>
			<th>Enunciado</th>
		</thead>

		<% @questions.each do |questions| %>
			<tr>
				<td class="align-center"><%= questions.year %></td>
				<td class="align-center"><%= link_to (questions.number, "/questions/#{questions.id}") %></td>
				<td><%= questions.area %></td>
				<td><%= truncate(questions.enunciation, length: 180, separator: ' ') %></td>
			</tr>

		<% end %>
	</table>

<% else %>

	<h3> Não há questões cadastradas no momento. </h3>

<% end %>

app/views/questions/languages.html.erb
<!--
  File: languages.erb
  Purpose: This View that show the languages category of the question.
  License : LGPL. No copyright.
 -->

<h1>Linguagens e Códigos e suas Tecnologias</h1>

<%= render :partial => 'category' %>

app/views/questions/math.html.erb
<!--
  File: math.erb
  Purpose: This View that show the math category of the question.
  License : LGPL. No copyright.
 -->

<h1>Matemática e suas Tecnologias</h1>

<%= render :partial => 'category' %>

app/views/questions/nature.html.erb
<!--
  File: nature.erb
  Purpose: This View that show the nature category of the question.
  License : LGPL. No copyright.
 -->

<h1>Ciências da Natureza e suas Tecnologias</h1>

<%= render :partial => 'category' %>

app/views/questions/new.html.erb
<!--
  File: new.erb
  Purpose: This View that show a new question for user.
  License : LGPL. No copyright.
 -->

<h1 class="border-title">Upload de Dados</h1>

<div class="content-container">
  <div class="upload-forms-container">
    <%= form_tag({ action: :upload_questions }, multipart: true, class: 'upload-form',
                   id: 'questions-form') do %>
      <h2 class="form-title">Questões em JSON</h2>
      <span class="btn btn-default btn-file">
        Browse<%= file_field_tag ('questions_file') %>
      </span>
      <%= submit_tag ('Enviar', class: 'btn btn-primary btn-sm') %>
    <% end %>

    <%= form_tag({ action: :upload_candidates_data }, multipart: true, class: 'upload-form', id: 'candidates-data-form') do %>
      <h2 class="form-title">Dados dos candidatos do Enem</h2>
      <%= select_tag :test_year, options_for_select((2009..2012).to_a.collect { |questions_file| questions_file.to_s }), class: 'form-control' %>
      <span class="btn btn-default btn-file">
        Browse<%= file_field_tag ('candidates_data_file') %>
      </span>
      <%= submit_tag ('Enviar', class: 'btn btn-primary btn-sm') %>
    <% end %>
  </div>

</div>

app/views/questions/recommended.html.erb
<!--
  File: recommended.erb
  Purpose: This View that show the recommended category of the question.
  License : LGPL. No copyright.
 -->

<h1>Questões Recomendadas</h1>

<%= render :partial => 'category' %>

app/views/questions/show.html.erb
<!--

  File: recommended.erb
  Purpose: This View that show the user performance at question.
  License : LGPL. No copyright.
 
 -->

<p></p>

<div class="buttons-questions">
  <% if current_user.role_admin? %>
    <%= link_to ("Editar", edit_question_path, class: "btn btn-primary", id: "btn-edit") %>
    <%= link_to ("Deletar", question_path, :method => :delete, class: "btn btn-danger", id: "btn-delete", data: { confirm: "Você tem certeza que deseja excluir esta questão?" }) %>
  <% end %>

</div>

<div class="question">
  <h1>Questão <%= @question.number%></h1>
  <h2>Ano: <%= @question.year %></h2>

  <div class='question-index'>
    <p><%= @question.area %></p>
  </div>

  <% @question.texts.each do |question| %>
    <h4 class="question-title"><%= question.title %></h4>
    <% question.paragraphs.each do |paragraphs| %>
      <p class="question-text"><%= paragraphs %></p>
    <% end %>
    
    <p class="question-text-reference"><%= question.reference %></p>
  <% end %>

  <% if !@ question.image.empty?%>
    <%= image_tag (@question.image , class: 'img-responsive question-img') %>
  <% end %>

    <%else%>
    <!-- nothing to do -->

  <p class="question"><%= @question.enunciation %></p>


  <%= form_tag answer_question_path, remote: true do %>
    <% @question.alternatives.each do |alternative| %>
      <div class="alternative">
        <%= radio_button_tag(:alternative, alternative.letter) %>
        <%= label_tag(alternative.letter.to_s, alternative.letter.to_s + ")") %>
        <span class="<%= alternative.letter.to_s %>-description"><%= alternative.description %></span>
      </div>
    <% end %>

  <%= submit_tag ("Responder", class: 'answer btn btn-primary btn-sm button', id: 'answer-btn') %>
  <%= link_to ("Pular", next_question_path, method: :post, class: 'btn btn-primary btn-sm button', id: 'jump-btn') %>

  <% end %>

<p>
  <%= yield :charts_js %>
  <%= bar_chart @question.data, colors: ["#009900", "#BBBB00" , "#0080FF"],
  min: 0,
  max: 100,
  library: {backgroundColor: "#eee",
            isStacked: true,
            title: 'Desempenho da Questão  (Porcentagem de acertos por tentativa)',

  } %>

</p>

</div>