config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get 'server_error' => 'static_pages#server_error'

  get 'signup' => 'users#new'
  get 'ranking' => 'users#ranking'
  get 'delete_profile_image' => 'users#delete_profile_image'
  get 'battles/ranking' => 'battles#ranking'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#log_user_in'
  delete 'logout' => 'sessions#log_user_out'

  get 'questions' => 'questions#category'
  get 'questions/all' => 'questions#index'

  get 'questions/humans' => 'questions#humans'
  get 'questions/nature' => 'questions#nature'
  get 'questions/languages' => 'questions#languages'
  get 'questions/math' => 'questions#math'
  get 'questions/recommended' => 'questions#recommended'
  get 'questions/upload' => 'questions#new'
  post 'questions/upload_questions'
  post 'questions/upload_candidates_data'

  get 'medals' => 'medals#index'

  get '/generate_random_user', :to=>"battles#generate_random_user"

  get 'notifications' => 'notifications#index'

  get 'answer_exam' => 'exams#answer_exam'
  get 'select_exam' => 'exams#select_exam'
  get 'exam_result' => 'exams#exam_result'
  get 'exams_statistics' => 'exams#exams_statistics'
  delete 'cancel_exam' => 'exams#cancel_exam'

  resources :posts
  resources :comments

  post 'comments/create' => 'comments#create'

  resources :topics
  resources :posts do
    resources :comments
  end

  resources :users
  resources :questions do
    member do
      post 'answer'
      post 'next' => 'questions#next_question'
    end
  end

  resources :battles do
    member do
      post 'answer'
      get 'finish'
    end
  end

  resources :posts do
    member do
      get 'rate_post' => 'posts#rate_post'
    end
  end

  resources :comments do
    member do
      get 'rate_comment' => 'comments#rate_comment'
    end
  end

  resources :battles do
    member do
      get 'result' => 'battles#result'
    end
  end

  resources :notifications do
    get :read, on: :collection
  end

  scope "(:locale)", locale: /en|nl/ do
    resources :users
    resources :battles
    resources :posts
    resources :comments
    resources :battles
    resources :altenatives
    resources :candidates
    resources :exams
    resources :medals
    resources :notifications
    resources :questions
    resources :texts
    resources :topics
  end

  get '*unmatched_route', :to => 'application#raise_not_found!'

end

app/models/topic.rb
# File: topic.rb
# Purpose: Implementation of topic's class 
# License : LGPL. No copyright.

# Post represents a user's post in a topic of forum. 
# Posts allow users to iniciate a discussion.

class Topic < ActiveRecord::Base

	validates :name, presence: true, uniqueness: true
	validates :description, presence: true, uniqueness: true

	has_many :posts
	
end

app/controllers/topics_controller.rb
# File: topics_controller.rb
# Purpose: Controller of topics. 
# License : LGPL. No copyright.

# This controller creates and shows a topic
# and require params of topics.

class TopicsController < ApplicationController

	include PostsHelper

	before_action :authenticate_user
	before_action :verify_user_permission, only: [:edit, :destroy]
  before_action :authenticate_admin, only: [ :new, :create, :edit, :destroy, :update ]

  # name: new
  # explanation: instantiates an object
  # parameters:
  # -none
  # return: a topic object

	def new
		@topic = Topic.new

    assert(@topic.kind_of?(Topic))

    return @topic
	end

  # name: create
  # explanation: creates a topic
  # parameters:
  # -none
  # return: redirect_to topic object

	def create
		@topic = Topic.new(topic_params)

    assert(@topic.kind_of?(Topic))

		if @topic.save
			flash[:success] = t(:create_topic)
			return redirect_to (@topic)
		else
      #nothing to do
    end

	end

  # name: show
  # explanation: show a topic
  # parameters:
  # -none
  # return: topic object

	def show
		@topic = Topic.find(params[:id])

    assert(@topic.kind_of?(Topic))

		session[:topic_id] = @topic.id
    session_topic = session[:topic_id]

    return session_topic
	end

	# name: index
  # explanation: list all topics
  # parameters:
  # -none
  # return: topics objects

	def index
		@topics = Topic.all
    return @topics
	end

	private

  # name: topic_params
  # explanation: require topic params
  # parameters:
  # -none
  # return: topic params hash

	def topic_params
		params.require(:topic).permit(:name, :description)
	end

end

app/views/topics/_form.html.erb
<!-- File: _form.html.erb 
Purpose: View of form to create a topic. 
License : LGPL. No copyright. -->

<%= form_for @topic do |f| -%>
	<%= f.label :name, "Nome" %>
	<%= f.text_field :name %>
	<%= f.label :description, "Descrição" %>
	<%= f.text_field :description %>
	<%= f.submit "Criar Tópico" %>
<% end -%>

app/views/topics/index.html.erb
<!-- File: index.html.erb
Purpose: Lists the existing comment to the relationated topic.
License : LGPL. No copyright. -->

<h1 class="content-title"> Fórum </h1>

<table class="table">
  <thead>
    <th>Questões</th>
    <th>Comentários</th>
  </thead>
  <tbody>
    <% @topics.each do |topic| %>
      <tr>
          <td>
            <%= link_to "#{topic.name}", "/topics/#{topic.id}" %>
            <ul><%= topic.description %></ul>
          </td>
          <td><%= topic.posts.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/topics/new.html.erb
<!-- File: new.html.erb
Purpose: Render form view.
License : LGPL. No copyright. -->

<%= render 'form' %>

app/views/topics/show.html.erb
<!-- File: show.html.erb 
Purpose: View to show topics 
License : LGPL. No copyright. -->

<!-- Topic introduction, contais name and description -->
<h1 class="content-title"> <%= @topic.name %></h1> 
<h2><%= @topic.description %></h2>

<div class="container-fluid">
  <ul class="list-group" id="posts-index">

    <% @topic.posts.each do |post| %>
      <li class="list-group-item">
        <div class="post-buttons" id="<%= "post_#{post.id}_div" -%>">

        <!-- User ratings -->
          <% if post.user_ratings.include? current_user.id %>
            <%= form_tag rate_post_post_path(post), remote: true do %>
              <%= button_tag " #{post.count_post_rates}", 
              class: "glyphicon glyphicon-thumbs-up btn btn-primary 
              rate-post-btn", id: post.id %>
          <% else %>
            <span class="btn btn-primary" id='rated-post' data-toggle="tooltip"
             title="Você já votou!">
             <%= "#{pluralize(post.count_post_rates,"voto","votos")}" %></span>
          <% end %>

          <!-- Set diferents dropdowns to the type of user -->
          <% if current_user.id == post.user_id  || current_user.role_admin? %>
            <div class="dropdown">
              <a href="#" class="btn btn-default glyphicon glyphicon-cog" 
              data-toggle="dropdown" id="dropdown-post-conf"></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Editar", edit_post_path(post, id: current_user.id, 
                post_id: post.id) %></li>
                <li><%= link_to "Excluir", post_path(post, id: current_user.id, post_id: post.id), 
                :method => :delete, data: { 
                confirm: "Você tem certeza que deseja excluir este post?" 
                } %></li>
              </ul>
            </div>
          <% end %>
        </div>

        <!-- Profile image to user -->
        <div class="side-contents">
          <div class="profile-image">
            <%= if post.user.profile_image_file_name.blank? %>
              <%= link_to post.user.profile_image_file_name, "profile_images/default" %>
            <%= else %>
              <%= link_to post.user.profile_image.url, "/users/#{post.user_id}" %>
            <% end %>
          </div>
          <span class="badge"><%= post.user.nickname %></span>
        </div>

        <p class="text-left" id="post-text"><%= post.content %></p>

        <!-- show comments of the topic -->
        <ul class="list-group">
        <% post.comments.each do |comment| %>
          <li class="list-group-item" id="comments-index">
            <div class="comments-buttons" id="<%= "comment_#{comment.id}_div" -%>">
              <% if comment.user_ratings.include? current_user.id %>
                <%= form_tag rate_comment_comment_path(comment), remote: true do %>
                  <%= button_tag " #{comment.count_comment_rates}", 
                  class: "glyphicon glyphicon-thumbs-up btn btn-primary rate-comment-btn", 
                  id: comment.id %>
              <% else %>
                <span class="btn btn-primary" id='rated-comment' data-toggle="tooltip" 
                title="Você já votou!"><%= "#{pluralize(comment.count_comment_rates,"voto","votos")}" %>
                </span>
              <% end %>

              <% if current_user.id == comment.user_id  || current_user.role_admin? %>
                <div class="dropdown">
                  <a href="#" class="btn btn-default glyphicon glyphicon-cog" data-toggle="dropdown" 
                  id="dropdown-comment-conf"></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Editar", edit_comment_path(comment, id: current_user.id, comment_id: comment.id) %></li>
                    <li><%= link_to "Excluir", comment_path(comment, id: current_user.id
                    ,comment_id: comment.id), method: :delete, data: { 
                    confirm: "Você tem certeza que deseja excluir este comentário?" 
                    } %></li>
                  </ul>
                </div>
              <% else %>
                <!-- nothing to do -->
              <% end %>

            </div>

            <div class="side-contents">
              <div class="profile-image">

              <%= if post.user.profile_image_file_name.blank? %>
                <%= link_to post.user.profile_image_file_name, "profile_images/default" %>
              <%= else %>
                <%= link_to post.user.profile_image.url, "/users/#{post.user_id}" %>
              <% end %>

              </div>

              <span class="badge"><%= comment.user.nickname %></span>
            </div>

            <p class="text-left" id="comment-text"><%= comment.content %></p>
          </li>
        <% end %>
        </ul>

        <div class="container-fluid" id="comment-text-area">

          <%= form_tag post_comments_path(post), id: 'comment-area' do %>
            <div id="cmnt-area"><%= text_area_tag "comment[content]", nil, 
            placeholder: "  Comente aqui..." %></div>
            <div id="cmnt-btn"><%= submit_tag "Comentar", class: "btn btn-success", 
            id: 'btn-comment-area' %></div>
          <% end %>

        </div>

      </li>
    <% end %>
  </ul>
</div>

<div class="container-fluid">
  <%= render "posts/new", method: new_post %>
</div>

<!-- Scripts code -->
<script type="text/javascript" language ="javascript" src="javascript/jquery.js"></script>

<script>
  $(document).ready(function(){
      $('[data-toggle="tooltip"]').tooltip();
  });

  $(function() {
    $(".rate-post-btn").click(function(evt) {
      var id = $(this).attr("id");
      $.ajax("/posts/"+ id + "/rate_post");
      $("#post_"+id+"_div").load(location.href + " #post_" + id + "_div")
      evt.preventDefault();
    })
  });

  $(function() {
    $(".rate-comment-btn").click(function(evt2) {
      var id = $(this).attr("id");
      $.ajax("/comments/"+ id + "/rate_comment");
      $("#comment_"+id+"_div").load(location.href + " #comment_" + id + "_div")
      evt2.preventDefault();
    })
  });
</script>