config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get 'server_error' => 'static_pages#server_error'

  get 'signup' => 'users#new'
  get 'ranking' => 'users#ranking'
  get 'delete_profile_image' => 'users#delete_profile_image'
  get 'battles/ranking' => 'battles#ranking'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#log_user_in'
  delete 'logout' => 'sessions#log_user_out'

  get 'questions' => 'questions#category'
  get 'questions/all' => 'questions#index'

  get 'questions/humans' => 'questions#humans'
  get 'questions/nature' => 'questions#nature'
  get 'questions/languages' => 'questions#languages'
  get 'questions/math' => 'questions#math'
  get 'questions/recommended' => 'questions#recommended'
  get 'questions/upload' => 'questions#new'
  post 'questions/upload_questions'
  post 'questions/upload_candidates_data'

  get 'medals' => 'medals#index'

  get '/generate_random_user', :to=>"battles#generate_random_user"

  get 'notifications' => 'notifications#index'

  get 'answer_exam' => 'exams#answer_exam'
  get 'select_exam' => 'exams#select_exam'
  get 'exam_result' => 'exams#exam_result'
  get 'exams_statistics' => 'exams#exams_statistics'
  delete 'cancel_exam' => 'exams#cancel_exam'

  resources :posts
  resources :comments

  post 'comments/create' => 'comments#create'

  resources :topics
  resources :posts do
    resources :comments
  end

  resources :users
  resources :questions do
    member do
      post 'answer'
      post 'next' => 'questions#next_question'
    end
  end

  resources :battles do
    member do
      post 'answer'
      get 'finish'
    end
  end

  resources :posts do
    member do
      get 'rate_post' => 'posts#rate_post'
    end
  end

  resources :comments do
    member do
      get 'rate_comment' => 'comments#rate_comment'
    end
  end

  resources :battles do
    member do
      get 'result' => 'battles#result'
    end
  end

  resources :notifications do
    get :read, on: :collection
  end

  scope "(:locale)", locale: /en|nl/ do
    resources :users
    resources :battles
    resources :posts
    resources :comments
    resources :battles
    resources :altenatives
    resources :candidates
    resources :exams
    resources :medals
    resources :notifications
    resources :questions
    resources :texts
    resources :topics
  end

  get '*unmatched_route', :to => 'application#raise_not_found!'

end

app/models/user.rb
# File: user.rb
# Purpose: Implementation of user's class
# License : LGPL. No copyright.

# The class user is the main class of the system, because it contains
# all information about one's progress in the website, in example place in
# ranking, number of right questions, etc

class User < ActiveRecord::Base
  NONE = 0
  BEGGINER = 30
  INTERMEDIATE = 60

  has_many :active_battles, class_name: 'Battle', foreign_key: 'player_1_id'
  has_many :passive_battles, class_name: 'Battle', foreign_key: 'player_2_id'
  has_many :won_battles, class_name: 'Battle', foreign_key: 'winner'
  has_many :notifications
  has_and_belongs_to_many :medals

  serialize :accepted_questions, Array
  serialize :answered_exams, Array
  serialize :tried_questions, Array
  serialize :exam_performance, Array

  before_save { self.email = email.downcase }

  has_secure_password

  has_attached_file :profile_image
  validates_attachment :profile_image,
      content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length:{maximum: 60}
  validates :nickname, presence: true, length:{maximum: 40}, uniqueness: true
  validates :email, presence: true, length:{maximum: 255},
  format: { with:  VALID_EMAIL },
  uniqueness: { case_sensitive: false }
  validates :password, length:{minimum: 8}, presence: true

  # name: User.digest
  # explanation: creates a safe encrypted password for user
  # parameters:
  # - string: password defined by user
  # return: none
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Password.create(string, cost: cost)
  end

  # name: count_questions_by_area
  # explanation: counts right questions of User in a given area
  # parameters:
  # - area: string that represents the area of the question
  # return: all right questions in the area
  def count_questions_by_area(area)
    right_questions_in_area = 0
    self.accepted_questions.each do |t|
      if Question.find(t).area == area
        right_questions_in_area = right_questions_in_area+1
      else
        # nothing to do
      end
    end
    return right_questions_in_area
  end

  # name: find_position_in_raking
  # explanation: Finds a user position in system's ranking by points
  # parameters:
  # - none
  # return: position in ranking
  def find_position_in_ranking
    ranking = User.all.order(:points).reverse
    for i in 0...ranking.count
      if ranking[i].id == self.id
        return i+1
      else
        # nothing to do
      end
    end
  end

  # name: total_accepted_questions
  # explanation: gets all right questions from a user
  # parameters:
  # - none
  # return: all right questions
  def total_accepted_questions
    all_right_questions = self.accepted_questions.count
    return all_right_questions
  end

  # name: data
  # explanation: creates info about all questions by area from user to use in system
  # parameters:
  # - none
  # return: none
  def data
    [
      ["Matemática", self.count_questions_by_area('matemática e suas tecnologias')],
      ["Natureza", self.count_questions_by_area('ciências da natureza e suas tecnologias')],
      ["Linguagens", self.count_questions_by_area('linguagens, códigos e suas tecnologias')],
      ["Humanas", self.count_questions_by_area('ciências humanas e suas tecnologias')]
    ]
  end

  # name: sum_exam_performance
  # explanation: creates info about the user's perfomance in all exams
  # parameters:
  # - none
  # return: exam performance updated
  def sum_exam_performance
    if self.exam_performance.empty?
      return 0
    else
      return self.exam_performance.inject(:+)
    end
  end

  # name: progress
  # explanation: checks a user's progress based on right questions by all questions
  # parameters:
  # - none
  # return: progress
  def progress
    progress_in_system = (100 * self.total_accepted_questions.to_f/Question.all.count).round(2)
    return progress_in_system
  end

  # name: battles
  # explanation: shows number of battles of a user
  # parameters:
  # - none
  # return: number of battles
  def battles
    battles = (self.active_battles + self.passive_battles).sort
    return battles
  end

  # name: average_performance
  # explanation: shows average performance in a given area by right questions by tried questions
  # parameters:
  # - area: String that represents the area of a question
  # return: average performance or 0.0
  def average_performance(area)
    accepted_questions = []
    tried_questions = []
    self.accepted_questions.each do |question_id|
      question_found = Question.find(question_id)
      if question_found.area == area
        accepted_questions << question_found
      else
        # nothing to do
      end
    end

    self.tried_questions.each do |question_id|
      question_found = Question.find(question_id)
      if question_found.area == area
        tried_questions << question_found
      else
        # nothing to do
      end
    end
    result = accepted_questions.count.to_f / tried_questions.count
    if result.nan?
      return 0.0
    else
      return result
    end
  end

  # name: classification
  # explanation:
  # parameters:
  # - area: String that represents the area of a question
  # return: String that specifies how good the user is
  def classification(area)
    performance = self.average_performance area
    performance *= 100


    if performance >= NONE && performance <= BEGGINER
     return "beginner"
   elsif performance > BEGGINER && performance <= INTERMEDIATE
     return "intermediate"
    else
     return "advanced"
    end
  end

end

app/controllers/users_controller.rb
# File: users_controller.rb
# Purpose: Maintain logic for users.
# License: LGPL. No copyright.

# This controller contain general methods regarding users objects, including
# actions to create, read, destroy, update users and create ranking for them,
# as well as actions regarding profile image.

class UsersController < ApplicationController

  @NONE = 0
  before_action :authenticate_user, except: [:ranking, :new, :create]
  before_action :verify_user_permission, only: [:edit, :destroy]

  # name: new
  # explanation: this method creates a new object of class User
  # parameters:
  # - none
  # return: if logged in, redirect to user's page.
  def new
    @home_page = true
    @user = User.new

    assert(@user.kind_of?(User))

    if logged_in?
        return redirect_to(current_user)
    else
    end
    # nothing to do
  end

  # name: edit
  # explanation: this method finds a user with a given id
  # parameters:
  # - none
  # return: returns the user found
  def edit
    @user = User.find(params[:id])

    assert(@user.kind_of?(User))

    return @user
  end

  # name: destroy
  # explanation: this method finds and destroy a User with given id
  # parameters:
  # - none
  # return: redirection to login
  def destroy
    assert(params[:id].kind_of?(Fixnum))

    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = t(:delete_user)
    return redirect_to(users_path)
  end

  # name: show
  # explanation: this method finds a user with a given id
  # parameters:
  # - none
  # return: Because of view, will redirect to a page with user's info
  def show
    assert(params[:id].kind_of?(Fixnum))

    @user = User.find(params[:id])

    assert(@user.kind_of?(User))

    return find_level(current_user.points)
  end

  # name: create
  # explanation: this method creates a user with info collected from a form
  # parameters:
  # - none
  # return: redirect's to homepage if success
  def create
    assert(!user_params.nil?)

    @user = User.new(user_params)

    if @user.save
      flash[:success] = t(:create_user)
      log_in(@user)
      first_notification
      return redirect_to(root_path)
    else
      @home_page = true
      return render('new')
    end
  end

  # name: destroy
  # explanation: this method gets user from edit and updates it's info
  # parameters:
  # - none
  # return: redirection to user's page
  def update
    assert(params[:id].kind_of?(Fixnum))

    @user = User.find(params[:id])

    assert(@user.kind_of?(User))

    if @user.update_attributes(user_params)
      flash[:success]= t(:update_user)
      return redirect_to(@user)
    else
      return render('edit')
    end
  end

  # name: destroy
  # explanation: this method gets all users from the system
  # parameters:
  # - none
  # return: Variable with all users
  def index
    @users = User.all
    return @users
  end

  # name: ranking
  # explanation: this method gets all users and ordem them based on their points
  # parameters:
  # - none
  # return: returns all users ordered
  def ranking
    if !logged_in?
      @home_page = true
    else
      # nothing to do
    end
      @users = User.order(:points).reverse
      return @users
  end

  # name: delete_profile_image
  # explanation: this method deletes a user's profile image
  # parameters:
  # - none
  # return: redirection to user's page
  def delete_profile_image
    if !current_user.profile_image_file_name.empty?
      current_user.update_attribute(:profile_image_file_name,"")
      flash[:success] = t(:delete_photo)
    else
      flash[:danger] = t(:error_delete_photo)
    end
    return redirect_to(user_path(current_user.id))
  end

  private

  # name: user_params
  # explanation: this method specifies what attributes can be collected in form
  # parameters:
  # - none
  # return: none
  def user_params
    params.require(:user).permit(:name, :email, :level, :points, :nickname, :password_digest,:password, :password_confirmation, :profile_image)
  end

end

app/helpers/users_helper.rb
# File: users_helper.rb
# Purpose: Maintain logic for users.
# License: LGPL. No copyright.

# This helper contains auxiliary methods to be used in the controller of ranking and level of the users. 


module UsersHelper

 # name: top10
 # explanation: this method the ten users with the highest score
 # parameters:
 # -none
 #return: ranking of enemamigo
  def top10
    ranking = User.all.order(:points).reverse
    @top10 = ranking.take(10)
  end

 # name: find_level
 # explanation: this method level of user without updating it
 # parameters:
 # -none
 #return: level of enemamigo
  def find_level user_points
    @user_level = (Math.sqrt 2*user_points).to_i
  end

 # name: update user level
 # explanation: this method update user level
 # parameters:
 # -none
 #return: level of enemamigo
  def update_user_level
    current_user.update_attribute(:level,@user_level)
    @user_level = current_user.level
  end
  
end

app/views/users/_form_errors.html.erb
<!--
 File: _form_errors.html.erb
 Purpose: This shows errors while trying to create a new user
 License : LGPL. No copyright.
-->

<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      O registro contém <%= pluralize(@user.errors.count, "erro", "erros") %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% else %>
  <!-- do nothing -->
<% end %>

app/views/users/_medals.html.erb
<!--
 File: _medals.html.erb
 Purpose: Shows a user's medal
 License : LGPL. No copyright.
-->

<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#medal_modal">Medalhas</button>

<div id="medal_modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">
          <% if @user.id == current_user.id %>
            Minhas medalhas
          <% else %>
           Medalhas de <%= @user.name %>
          <% end %>
         </h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <% if !@user.medals.empty? %>
            <% @user.medals.each do |medal| %>
              <div class="col-sm-6 col-md-3">
                <div class="thumbnail" id="user_medals">
                  <%= image_tag(medal.image) %>
                  <p class="medal_name">
                    <b><%= medal.name %></b>
                  </p>
                  <p class="medal_description">
                    <%= medal.description %>
                  </p>
                </div>
              </div>
            <% end %>
          <% else %>
            <% if @user.id == current_user.id %>
              Você
            <% else %>
              <%= @user.name %>
            <% end %>
            não tem nenhuma medalha
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>

  </div>
</div>

app/views/users/_new_level.html.erb
<!--
 File: _new_level.html.erb
 Purpose: View that congratulates user for getting to another level
 License : LGPL. No copyright.
-->

<div id="new_level_modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Parabéns!!! Você alcançou o nível <%= @user_level %></h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<script>
  $('#new_level_modal').modal('show');
</script>

app/views/users/_profile_sidebar.html.erb
<!--
 File: _profile_sidebar.html.erb
 Purpose: Sidebar of the system that shows basic informations about user
 License : LGPL. No copyright.
-->

<div class="col-sm-3">
  <div class="profile-sidebar">
    <div class="profile-image">

        <% if current_user.profile_image_file_name.blank? %>
          <%= link_to(image_tag("profiles_images/default")) %>
        <% else %>
          <%= link_to(image_tag(current_user.profile_image.url, alt: "Profile image"), "/users/#{current_user.id}") %>
        <% end %>

    </div>

    <div class="profile-information">
      <p id="user-name"><%= current_user.name %></p>
      <p id="user-level"><strong><%= t(:'users._profile_sidebar.level')%>: </strong> <%= current_user.level %></p>
      <p id="user-rank"><strong><%= t(:'users._profile_sidebar.position')%>: </strong> <%= current_user.find_position_in_ranking %>º</p>
      <p><strong><%= t(:'users._profile_sidebar.resolved')%>:</strong> <%= pluralize(current_user.total_accepted_questions, 'questão' ,'questões')%></p>
      <%= link_to(t(:'users._profile_sidebar.score'), exams_statistics_path, class: 'btn btn-primary', id:'statistics') %>
      <a href="/medals" class="btn btn-success"><%= image_tag("star.png") %><span><%= t(:'users._profile_sidebar.medal')%></span></a>
    </div>

    <%= render 'users/ranking' %>

  </div>
</div>

app/views/users/_ranking.html.erb
<!--
 File: _ranking.html.erb
 Purpose: The 10 best users of application
 License : LGPL. No copyright.
-->

<table class="ranking">

  <thead>
    <tr class="clickable-row" data-href=<%= ranking_path %> >
      <th><%= link_to(image_tag("trophy.jpg"), ranking_path) %> <span>TOP 10</span></th>
    </tr>
  </thead>

  <tbody>
  <% top10.each do |users| %>
    <tr>
      <td><%= link_to(users.name, "/users/#{users.id}") %></td>
    </tr>
  <% end %>
  </tbody>

</table>

app/views/users/battle_ranking.html.erb
<!--
 File: battle_ranking.html.erb
 Purpose: Ranking that shows users and their situation in battles
 License : LGPL. No copyright.
-->

<h1>Ranking da Batalha</h1>

<table class="table">
  <thead>
    <th>Posição</th>
    <th>Nome</th>
    <th>Pontos da Batalha</th>
    <th>Batalhas vencidas</th>
  </thead>
  <tbody>
    <% i = 0 %>
    <% @users.each do |user| %>
    <tr>
        <td><%= i = i+1 %>º</td>
        <td><%= link_to(user.name, "/users/#{user.id}") %></td>
        <td><%= user.battle_points %></td>
        <td><%= user.wins %></td>
    </tr>
    <% end %>
    </tbody>
</table>

app/views/users/edit.html.erb
<!--
 File: edit.html.erb
 Purpose: Form to collect information to update a user
 License : LGPL. No copyright.
-->

<h1> Alterar Dados </h1>

<%= render 'form_errors' %>

<%= form_for(@user) do |form| %>
  <%= form.label(:nickname, "Nome de Usuário") %>
  <%= form.text_field(:nickname, class: 'form-control') %>
  <%= form.label(:name, "Nome Completo") %>
  <%= form.text_field(:name, class: 'form-control') %>
  <%= form.label(:email, "E-mail") %>
  <%= form.text_field(:email, class: 'form-control') %>
  <%= form.label(:password, "Senha") %>
  <%= form.password_field(:password, class: 'form-control') %>
  <%= form.label(:password_confirmation, "Confirmar senha") %>
  <%= form.password_field(:password_confirmation, class: 'form-control') %>
  <div>
    <%= form.label(:profile_image, "Foto de Perfil") %>
    <% if !current_user.profile_image_file_name.blank? %>
      <%= link_to('Remover foto', delete_profile_image_path, class: 'btn btn-danger', id: 'delete-image', data: { confirm: "Você tem certeza que deseja remover a foto?" }) %>
    <% else %>
      <!-- nothing to do -->
    <% end %>
  </div>
  <span class="btn btn-default btn-file">
    Browse<%= form.file_field(:profile_image, class: 'form-control') %>
  </span>
  <%= form.submit("Atualizar Dados", class: 'btn btn-primary') %>

<% end %>

app/views/users/index.html.erb
<!--
 File: index.html.erb
 Purpose: View that shows all users
 License : LGPL. No copyright.
-->

<h1> Usuários </h1>

<table class="table">
  <thead>
    <th>Nome</th>
    <th>Nível</th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
        <td><%= link_to("#{user.name}", "/users/#{user.id}") %></td>
        <td><%= user.level %></td>
    </tr>
    <% end %>
    </tbody>
</table>

app/views/users/new.html.erb
<!--
 File: new.html.erb
 Purpose: Form to collect information to create a user
 License : LGPL. No copyright.
-->

<h1>Cadastro</h1>

<%= render('form_errors') %>

<%= form_for(@user) do |form| %>
  <%= form.label(:nickname, "Nome de Usuário") %>
  <%= form.text_field(:nickname, class: 'form-control') %>
  <%= form.label(:name, "Nome Completo") %>
  <%= form.text_field(:name, class: 'form-control') %>
  <%= form.label(:email, "E-mail") %>
  <%= form.text_field(:email, class: 'form-control') %>
  <%= form.label(:password, "Senha") %>
  <%= form.password_field(:password, class: 'form-control') %>
  <%= form.label(:password_confirmation, "Confirmar senha") %>
  <%= form.password_field(:password_confirmation, class: 'form-control') %>
  <div>
    <%= form.label(:profile_image, "Foto de Perfil") %>
  </div>
  <span class="btn btn-default btn-file">
    Browse<%= form.file_field(:profile_image, class: 'form-control') %>
  </span>
  <%= form.submit("Cadastrar", class: 'btn btn-primary') %>

<% end %>

app/views/users/ranking.html.erb
<!--
 File: ranking.html.erb
 Purpose: Ranking with best users
 License : LGPL. No copyright.
-->

<h1>Ranking Geral</h1>

<table class="table">
  <thead>
    <th>Posição</th>
    <th>Nome</th>
    <th>Pontos</th>
    <th>Nível</th>
  </thead>
  <tbody>
    <% i = 0 %>
    <% @users.each do |user| %>
    <tr>
        <td><%= i = i+1 %>º</td>
        <td><%= link_to(user.name, "/users/#{user.id}") %></td>
        <td><%= user.points %></td>
        <td><%= user.level %></td>
    </tr>
    <% end %>
    </tbody>
</table>

app/views/users/show.html.erb
<!--
 File: show.html.erb
 Purpose: Page about a user with his most important information
 License : LGPL. No copyright.
-->


<% if @user_level != current_user.level %>
    <%= render partial: 'users/new_level.html.erb' %>
    <% update_user_level %>
<% else %>
  <!-- nothing to do -->
<% end %>

<div class="buttons-questions">
  <% if(current_user.role_admin? || current_user.id == @user.id) %>
    <%= link_to("Editar", edit_user_path, class: "btn btn-primary") %>
    <%= link_to("Excluir", user_path, :method => :delete,  class: "btn btn-danger", data: { confirm: "Você tem certeza que deseja excluir seu usuário?" }) %>
  <% else %>
    <!-- nothing to do -->
  <% end %>
</div>

<h1><%= @user.name %></h1>

<% if !@user.accepted_questions.blank? %>
  <%= pie_chart @user.data, colors: ["red", "#0080FF" , "#009900", "#EEEE00"] %>
<% else %>
  <h4 id="no-questions"><center>Você ainda não respondeu nenhuma questão</center></h4>
<% end %>

<table class="table">
  <tr>
    <td><b>Usuário:</b> <%= @user.nickname %></td>
  </tr>
  <tr>
    <td><b>Nível:</b> <%= @user.level %></td>
  </tr>
  <tr>
    <td><b>Membro desde:</b> <%= @user.created_at.strftime(" %d/%m/%Y ") %></td>
  </tr>
  <tr>
    <td><b>Pontos:</b> <%= @user.points %></td>
  </tr>
</table>


<div>
  <div class="row">
    <% @user.medals.reverse.take(4).each do |medal| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail" id="user_medals">
          <%= image_tag(medal.image) %>
          <p class="medal_name">
            <b><%= medal.name %></b>
          </p>
          <p class="medal_description">
            <%= medal.description %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render partial: 'medals' %>

<div>
  <p>
    <b>Questões resolvidas: </b>
    <%= @user.total_accepted_questions %>
  </p>

  <% if @user.total_accepted_questions != @NONE %>
    <table class = 'table'>
      <thead>
        <th>Número</th>
        <th>Área</th>
        <th>Ano</th>
      </thead>
      <% @user.accepted_questions.each do |right_question| %>
        <% accepted = Question.find(right_question) %>
        <tbody>
          <td><%= link_to "#{accepted.number}", "/questions/#{right_question}" %></td>
          <td><%= accepted.area %></td>
          <td><%= accepted.year %></td>
        </tbody>
      <% end %>
    </table>
  <% else %>
    <!-- nothing to do -->
  <% end %>
</div>